apiVersion: v1
kind: Service
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  type: NodePort
  ports:
    - port: 3000           # Exposed inside the cluster
      targetPort: 3000     # Container port
      nodePort: 30892      # Fixed external port (must be in 30000–32767)
  selector:
    app: zomato

